name: Database Setup

on:
  workflow_dispatch:

jobs:
  database:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install dependencies
        run: npm install

      - name: Generate Prisma Client
        run: npx prisma generate
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}

      - name: Push Prisma schema to database
        run: npx prisma db push
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
